package model.entities;
// Generated 12-Jun-2015 00:00:28 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ActividadDocentes generated by hbm2java
 */
public class ActividadDocentes  implements java.io.Serializable {


     private int id;
     private Designaciones designaciones;
     private Date fecha;
     private String asignatura;
     private Boolean visadoBedelia;
     private String observaciones;
     private int idUnidadAcademica;
     private String idMateria;
     private String carrera;
     private int idComision;

    public ActividadDocentes() {
    }

	
    public ActividadDocentes(Designaciones designaciones) {
        this.designaciones = designaciones;
    }
    public ActividadDocentes(Designaciones designaciones, Date fecha, String asignatura, Boolean visadoBedelia, String observaciones, int idUnidadAcademica, String idMateria, String carrera, int idComision) {
       this.designaciones = designaciones;
       this.fecha = fecha;
       this.asignatura = asignatura;
       this.visadoBedelia = visadoBedelia;
       this.observaciones = observaciones;
       this.idUnidadAcademica = idUnidadAcademica;
       this.idMateria = idMateria;
       this.carrera = carrera;
       this.idComision = idComision;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Designaciones getDesignaciones() {
        return this.designaciones;
    }
    
    public void setDesignaciones(Designaciones designaciones) {
        this.designaciones = designaciones;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(String asignatura) {
        this.asignatura = asignatura;
    }
    public Boolean getVisadoBedelia() {
        return this.visadoBedelia;
    }
    
    public void setVisadoBedelia(Boolean visadoBedelia) {
        this.visadoBedelia = visadoBedelia;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public int getIdUnidadAcademica() {
        return this.idUnidadAcademica;
    }
    
    public void setIdUnidadAcademica(int idUnidadAcademica) {
        this.idUnidadAcademica = idUnidadAcademica;
    }
    public String getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(String idMateria) {
        this.idMateria = idMateria;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public int getIdComision() {
        return this.idComision;
    }
    
    public void setIdComision(int idComision) {
        this.idComision = idComision;
    }




}


