package model.entities;
// Generated 12-Jun-2015 00:00:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Areas generated by hbm2java
 */
public class Areas  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Integer orden;
     private Set registrosUnicoses = new HashSet(0);
     private Set usuarioses = new HashSet(0);

    public Areas() {
    }

    public Areas(String nombre, Integer orden, Set registrosUnicoses, Set usuarioses) {
       this.nombre = nombre;
       this.orden = orden;
       this.registrosUnicoses = registrosUnicoses;
       this.usuarioses = usuarioses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
    public Set getRegistrosUnicoses() {
        return this.registrosUnicoses;
    }
    
    public void setRegistrosUnicoses(Set registrosUnicoses) {
        this.registrosUnicoses = registrosUnicoses;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


