package model.entities;
// Generated 12-Jun-2015 00:00:28 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ComprobantesTraslados generated by hbm2java
 */
public class ComprobantesTraslados  implements java.io.Serializable {


     private int id;
     private Comprobantes comprobantes;
     private String desde;
     private String hasta;
     private Date fechaHoraSalida;

    public ComprobantesTraslados() {
    }

	
    public ComprobantesTraslados(Comprobantes comprobantes) {
        this.comprobantes = comprobantes;
    }
    public ComprobantesTraslados(Comprobantes comprobantes, String desde, String hasta, Date fechaHoraSalida) {
       this.comprobantes = comprobantes;
       this.desde = desde;
       this.hasta = hasta;
       this.fechaHoraSalida = fechaHoraSalida;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Comprobantes getComprobantes() {
        return this.comprobantes;
    }
    
    public void setComprobantes(Comprobantes comprobantes) {
        this.comprobantes = comprobantes;
    }
    public String getDesde() {
        return this.desde;
    }
    
    public void setDesde(String desde) {
        this.desde = desde;
    }
    public String getHasta() {
        return this.hasta;
    }
    
    public void setHasta(String hasta) {
        this.hasta = hasta;
    }
    public Date getFechaHoraSalida() {
        return this.fechaHoraSalida;
    }
    
    public void setFechaHoraSalida(Date fechaHoraSalida) {
        this.fechaHoraSalida = fechaHoraSalida;
    }

}


