package model.entities;
// Generated May 17, 2015 2:44:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ComprobantesTraslados generated by hbm2java
 */
public class ComprobantesTraslados  implements java.io.Serializable {


     private int id;
     private Comprobantes comprobantes;
     private String desde;
     private String hasta;
     private Date fechaHoraSalida;
     private Date fechaHoraRegreso;

    public ComprobantesTraslados() {
    }

	
    public ComprobantesTraslados(int id, Comprobantes comprobantes) {
        this.id = id;
        this.comprobantes = comprobantes;
    }
    public ComprobantesTraslados(int id, Comprobantes comprobantes, String desde, String hasta, Date fechaHoraSalida, Date fechaHoraRegreso) {
       this.id = id;
       this.comprobantes = comprobantes;
       this.desde = desde;
       this.hasta = hasta;
       this.fechaHoraSalida = fechaHoraSalida;
       this.fechaHoraRegreso = fechaHoraRegreso;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Comprobantes getComprobantes() {
        return this.comprobantes;
    }
    
    public void setComprobantes(Comprobantes comprobantes) {
        this.comprobantes = comprobantes;
    }
    public String getDesde() {
        return this.desde;
    }
    
    public void setDesde(String desde) {
        this.desde = desde;
    }
    public String getHasta() {
        return this.hasta;
    }
    
    public void setHasta(String hasta) {
        this.hasta = hasta;
    }
    public Date getFechaHoraSalida() {
        return this.fechaHoraSalida;
    }
    
    public void setFechaHoraSalida(Date fechaHoraSalida) {
        this.fechaHoraSalida = fechaHoraSalida;
    }
    public Date getFechaHoraRegreso() {
        return this.fechaHoraRegreso;
    }
    
    public void setFechaHoraRegreso(Date fechaHoraRegreso) {
        this.fechaHoraRegreso = fechaHoraRegreso;
    }




}


