package model.entities;
// Generated 12-Jun-2015 00:00:28 by Hibernate Tools 4.3.1



/**
 * ComprobantesComidaAlojamientos generated by hbm2java
 */
public class ComprobantesComidaAlojamientos  implements java.io.Serializable {


     private int id;
     private Comprobantes comprobantes;
     private short tipo;
     private String descripcion;

    public ComprobantesComidaAlojamientos() {
    }

	
    public ComprobantesComidaAlojamientos(Comprobantes comprobantes, short tipo) {
        this.comprobantes = comprobantes;
        this.tipo = tipo;
    }
    public ComprobantesComidaAlojamientos(Comprobantes comprobantes, short tipo, String descripcion) {
       this.comprobantes = comprobantes;
       this.tipo = tipo;
       this.descripcion = descripcion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Comprobantes getComprobantes() {
        return this.comprobantes;
    }
    
    public void setComprobantes(Comprobantes comprobantes) {
        this.comprobantes = comprobantes;
    }
    public short getTipo() {
        return this.tipo;
    }
    
    public void setTipo(short tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


