package model.entities;
// Generated 12-Jun-2015 00:00:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Designaciones generated by hbm2java
 */
public class Designaciones  implements java.io.Serializable {


     private int id;
     private Solicitudes solicitudes;
     private String numeroResolucion;
     private String categoria;
     private Date desde;
     private Date hasta;
     private String observaciones;
     private Integer idDesignacion;
     private Date fecNorma;
     private Set actividadDocenteses = new HashSet(0);

    public Designaciones() {
    }

    public Designaciones(int id, Solicitudes solicitudes, String numeroResolucion, String categoria, Date desde, Date hasta, String observaciones, int idDesignacion, Date fecNorma) {
        this.id = id;
        this.solicitudes = solicitudes;
        this.numeroResolucion = numeroResolucion;
        this.categoria = categoria;
        this.desde = desde;
        this.hasta = hasta;
        this.observaciones = observaciones;
        this.idDesignacion = idDesignacion;
        this.fecNorma = fecNorma;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Solicitudes getSolicitudes() {
        return this.solicitudes;
    }
    
    public void setSolicitudes(Solicitudes solicitudes) {
        this.solicitudes = solicitudes;
    }
    public String getNumeroResolucion() {
        return this.numeroResolucion;
    }
    
    public void setNumeroResolucion(String numeroResolucion) {
        this.numeroResolucion = numeroResolucion;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Date getDesde() {
        return this.desde;
    }
    
    public void setDesde(Date desde) {
        this.desde = desde;
    }
    public Date getHasta() {
        return this.hasta;
    }
    
    public void setHasta(Date hasta) {
        this.hasta = hasta;
    }
    
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public Integer getIdDesignacion() {
        return idDesignacion;
    }

    public void setIdDesignacion(Integer idDesignacion) {
        this.idDesignacion = idDesignacion;
    }

    public Date getFecNorma() {
        return fecNorma;
    }

    public void setFecNorma(Date fecNorma) {
        this.fecNorma = fecNorma;
    }
    
    public Set getActividadDocenteses() {
        return this.actividadDocenteses;
    }
    
    public void setActividadDocenteses(Set actividadDocenteses) {
        this.actividadDocenteses = actividadDocenteses;
    }

    


}


