package model.entities;
// Generated 12-Jun-2015 00:00:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Designaciones generated by hbm2java
 */
public class Designaciones  implements java.io.Serializable {


     private int id;
     private Solicitudes solicitudes;
     private String numeroResolucion;
     private String categoria;
     private Date desde;
     private Date hasta;
     private String dedicacion;
     private String observaciones;
     private int idComision;
     private Set actividadDocenteses = new HashSet(0);

    public Designaciones() {
    }

	
    public Designaciones(Solicitudes solicitudes) {
        this.solicitudes = solicitudes;
    }
    public Designaciones(Solicitudes solicitudes, String numeroResolucion, String categoria, Date desde, Date hasta, String dedicacion, String observaciones, Set actividadDocenteses) {
       this.solicitudes = solicitudes;
       this.numeroResolucion = numeroResolucion;
       this.categoria = categoria;
       this.desde = desde;
       this.hasta = hasta;
       this.dedicacion = dedicacion;
       this.observaciones = observaciones;
       this.actividadDocenteses = actividadDocenteses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Solicitudes getSolicitudes() {
        return this.solicitudes;
    }
    
    public void setSolicitudes(Solicitudes solicitudes) {
        this.solicitudes = solicitudes;
    }
    public String getNumeroResolucion() {
        return this.numeroResolucion;
    }
    
    public void setNumeroResolucion(String numeroResolucion) {
        this.numeroResolucion = numeroResolucion;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Date getDesde() {
        return this.desde;
    }
    
    public void setDesde(Date desde) {
        this.desde = desde;
    }
    public Date getHasta() {
        return this.hasta;
    }
    
    public void setHasta(Date hasta) {
        this.hasta = hasta;
    }
    public String getDedicacion() {
        return this.dedicacion;
    }
    
    public void setDedicacion(String dedicacion) {
        this.dedicacion = dedicacion;
    }

    public int getIdComision() {
        return idComision;
    }

    public void setIdComision(int idComision) {
        this.idComision = idComision;
    }
    
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set getActividadDocenteses() {
        return this.actividadDocenteses;
    }
    
    public void setActividadDocenteses(Set actividadDocenteses) {
        this.actividadDocenteses = actividadDocenteses;
    }




}


