package model.entities;
// Generated 12-Jun-2015 00:00:28 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Docentes generated by hbm2java
 */
public class Docentes  implements java.io.Serializable {


     private int id;
     private Solicitudes solicitudes;
     private String nombre;
     private String apellido;
     private String dni;
     private String telefonoFijo;
     private String telefonoCelular;
     private String email;
     private String lugarResidencia;
     private String motivoComision;
     private Date fechaInicio;
     private Date fechaFinalizacion;
     private String observaciones;
     private String cuil;

    public Docentes() {
    }

	
    public Docentes(Solicitudes solicitudes) {
        this.solicitudes = solicitudes;
    }
    public Docentes(Solicitudes solicitudes, String nombre, String apellido, String dni, String telefonoF,String telefonoC, String email, String lugarResidencia, String motivoComision, Date fechaInicio, Date fechaFinalizacion, String observaciones,String cuil) {
       this.solicitudes = solicitudes;
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.telefonoFijo = telefonoF;
       this.telefonoCelular = telefonoC;
       this.email = email;
       this.lugarResidencia = lugarResidencia;
       this.motivoComision = motivoComision;
       this.fechaInicio = fechaInicio;
       this.fechaFinalizacion = fechaFinalizacion;
       this.observaciones = observaciones;
       this.cuil = cuil;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Solicitudes getSolicitudes() {
        return this.solicitudes;
    }
    
    public void setSolicitudes(Solicitudes solicitudes) {
        this.solicitudes = solicitudes;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefono) {
        this.telefonoFijo = telefono;
    }

    public String getTelefonoCelular() {
        return telefonoCelular;
    }

    public void setTelefonoCelular(String telefonoCelular) {
        this.telefonoCelular = telefonoCelular;
    }
    
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLugarResidencia() {
        return this.lugarResidencia;
    }
    
    public void setLugarResidencia(String lugarResidencia) {
        this.lugarResidencia = lugarResidencia;
    }
    public String getMotivoComision() {
        return this.motivoComision;
    }
    
    public void setMotivoComision(String motivoComision) {
        this.motivoComision = motivoComision;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFinalizacion() {
        return this.fechaFinalizacion;
    }
    
    public void setFechaFinalizacion(Date fechaFinalizacion) {
        this.fechaFinalizacion = fechaFinalizacion;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public String getCuil() {
        return cuil;
    }

    public void setCuil(String cuil) {
        this.cuil = cuil;
    }

}


