package model.entities;
// Generated 12-Jun-2015 00:00:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estados generated by hbm2java
 */
public class Estados  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set registrosUnicoses = new HashSet(0);

    public Estados() {
    }

    public Estados(int id, String nombre, Set reg) {
        this.id = id;
        this.nombre = nombre;
        this.registrosUnicoses = reg;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getRegistrosUnicoses() {
        return this.registrosUnicoses;
    }
    
    public void setRegistrosUnicoses(Set registrosUnicoses) {
        this.registrosUnicoses = registrosUnicoses;
    }




}


