package model.entities;
// Generated May 17, 2015 2:44:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Expedientes generated by hbm2java
 */
public class Expedientes  implements java.io.Serializable {


     private int id;
     private String numeroExpediente;
     private Date fecha;
     private Set expedientesSolicitudeses = new HashSet(0);

    public Expedientes() {
    }

	
    public Expedientes(int id) {
        this.id = id;
    }
    public Expedientes(int id, String numeroExpediente, Date fecha, Set expedientesSolicitudeses) {
       this.id = id;
       this.numeroExpediente = numeroExpediente;
       this.fecha = fecha;
       this.expedientesSolicitudeses = expedientesSolicitudeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNumeroExpediente() {
        return this.numeroExpediente;
    }
    
    public void setNumeroExpediente(String numeroExpediente) {
        this.numeroExpediente = numeroExpediente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getExpedientesSolicitudeses() {
        return this.expedientesSolicitudeses;
    }
    
    public void setExpedientesSolicitudeses(Set expedientesSolicitudeses) {
        this.expedientesSolicitudeses = expedientesSolicitudeses;
    }




}


