package model.entities;
// Generated 12-Jun-2015 00:00:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Expedientes generated by hbm2java
 */
public class Expedientes  implements java.io.Serializable {


     private int id;
     private String numeroExpediente;
     private Date fecha;
     private Estados estados;
     private Areas areas;
     private Set expedientesSolicitudeses = new HashSet(0);

    public Expedientes() {
    }

    public Expedientes(int id,String numeroExpediente, Date fecha,Areas area,Estados estado, Set expedientesSolicitudeses) {
       this.id = id;
       this.numeroExpediente = numeroExpediente;
       this.fecha = fecha;
       this.estados = estado;
       this.areas = area;
       this.expedientesSolicitudeses = expedientesSolicitudeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNumeroExpediente() {
        return this.numeroExpediente;
    }
    
    public void setNumeroExpediente(String numeroExpediente) {
        this.numeroExpediente = numeroExpediente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getExpedientesSolicitudeses() {
        return this.expedientesSolicitudeses;
    }
    
    public void setExpedientesSolicitudeses(Set expedientesSolicitudeses) {
        this.expedientesSolicitudeses = expedientesSolicitudeses;
    }

    public Estados getEstados() {
        return estados;
    }

    public void setEstados(Estados estados) {
        this.estados = estados;
    }

    public Areas getAreas() {
        return areas;
    }

    public void setAreas(Areas areas) {
        this.areas = areas;
    }




}


