package model.entities;
// Generated May 17, 2015 2:44:47 AM by Hibernate Tools 4.3.1



/**
 * ExpedientesSolicitudes generated by hbm2java
 */
public class ExpedientesSolicitudes  implements java.io.Serializable {


     private int id;
     private Expedientes expedientes;
     private Solicitudes solicitudes;

    public ExpedientesSolicitudes() {
    }

    public ExpedientesSolicitudes(int id, Expedientes expedientes, Solicitudes solicitudes) {
       this.id = id;
       this.expedientes = expedientes;
       this.solicitudes = solicitudes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Expedientes getExpedientes() {
        return this.expedientes;
    }
    
    public void setExpedientes(Expedientes expedientes) {
        this.expedientes = expedientes;
    }
    public Solicitudes getSolicitudes() {
        return this.solicitudes;
    }
    
    public void setSolicitudes(Solicitudes solicitudes) {
        this.solicitudes = solicitudes;
    }




}


