package model.entities;
// Generated 12-Jun-2015 00:00:28 by Hibernate Tools 4.3.1



/**
 * Liquidaciones generated by hbm2java
 */
public class Liquidaciones  implements java.io.Serializable {


     private int id;
     private Solicitudes solicitudes;
     private Float reconocimientoGastoComida;
     private Float reconocimientoGastoAlojamiento;
     private Float reconocimientoGastoCombustible;
     private Float reconocimientoGastoPasajes;
     private Float importeDeclarado;
     private Float reconocimientoImporteTotal;
     private String observaciones;

    public Liquidaciones() {
    }

	
    public Liquidaciones(Solicitudes solicitudes) {
        this.solicitudes = solicitudes;
    }
    public Liquidaciones(Solicitudes solicitudes, Float reconocimientoGastoComida, Float reconocimientoGastoAlojamiento, Float reconocimientoGastoCombustible, Float reconocimientoGastoPasajes, Float importeDeclarado, Float reconocimientoImporteTotal, String observaciones) {
       this.solicitudes = solicitudes;
       this.reconocimientoGastoComida = reconocimientoGastoComida;
       this.reconocimientoGastoAlojamiento = reconocimientoGastoAlojamiento;
       this.reconocimientoGastoCombustible = reconocimientoGastoCombustible;
       this.reconocimientoGastoPasajes = reconocimientoGastoPasajes;
       this.importeDeclarado = importeDeclarado;
       this.reconocimientoImporteTotal = reconocimientoImporteTotal;
       this.observaciones = observaciones;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Solicitudes getSolicitudes() {
        return this.solicitudes;
    }
    
    public void setSolicitudes(Solicitudes solicitudes) {
        this.solicitudes = solicitudes;
    }
    public Float getReconocimientoGastoComida() {
        return this.reconocimientoGastoComida;
    }
    
    public void setReconocimientoGastoComida(Float reconocimientoGastoComida) {
        this.reconocimientoGastoComida = reconocimientoGastoComida;
    }
    public Float getReconocimientoGastoAlojamiento() {
        return this.reconocimientoGastoAlojamiento;
    }
    
    public void setReconocimientoGastoAlojamiento(Float reconocimientoGastoAlojamiento) {
        this.reconocimientoGastoAlojamiento = reconocimientoGastoAlojamiento;
    }
    public Float getReconocimientoGastoCombustible() {
        return this.reconocimientoGastoCombustible;
    }
    
    public void setReconocimientoGastoCombustible(Float reconocimientoGastoCombustible) {
        this.reconocimientoGastoCombustible = reconocimientoGastoCombustible;
    }
    public Float getReconocimientoGastoPasajes() {
        return this.reconocimientoGastoPasajes;
    }
    
    public void setReconocimientoGastoPasajes(Float reconocimientoGastoPasajes) {
        this.reconocimientoGastoPasajes = reconocimientoGastoPasajes;
    }
    public Float getImporteDeclarado() {
        return this.importeDeclarado;
    }
    
    public void setImporteDeclarado(Float importeDeclarado) {
        this.importeDeclarado = importeDeclarado;
    }
    public Float getReconocimientoImporteTotal() {
        return this.reconocimientoImporteTotal;
    }
    
    public void setReconocimientoImporteTotal(Float reconocimientoImporteTotal) {
        this.reconocimientoImporteTotal = reconocimientoImporteTotal;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


