package model.entities;
// Generated 12-Jun-2015 00:00:28 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RegistrosUnicos generated by hbm2java
 */
public class RegistrosUnicos  implements java.io.Serializable {


     private int id;
     private Areas areas;
     private Estados estados;
     private Solicitudes solicitudes;
     private Date fechaEntrada;
     private Date fechaSalida;
     private Boolean confirmado;
     private String observaciones;

    public RegistrosUnicos() {
    }

	
    public RegistrosUnicos(Areas areas, Estados estados, Solicitudes solicitudes) {
        this.areas = areas;
        this.estados = estados;
        this.solicitudes = solicitudes;
    }
    public RegistrosUnicos(int id,Areas areas, Estados estados, Solicitudes solicitudes, Date fechaEntrada, Date fechaSalida, Boolean confirmado, String observaciones) {
       this.id = id;
       this.areas = areas;
       this.estados = estados;
       this.solicitudes = solicitudes;
       this.fechaEntrada = fechaEntrada;
       this.fechaSalida = fechaSalida;
       this.confirmado = confirmado;
       this.observaciones = observaciones;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Areas getAreas() {
        return this.areas;
    }
    
    public void setAreas(Areas areas) {
        this.areas = areas;
    }
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }
    public Solicitudes getSolicitudes() {
        return this.solicitudes;
    }
    
    public void setSolicitudes(Solicitudes solicitudes) {
        this.solicitudes = solicitudes;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public Boolean getConfirmado() {
        return this.confirmado;
    }
    
    public void setConfirmado(Boolean confirmado) {
        this.confirmado = confirmado;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


