package model.entities;
// Generated 12-Jun-2015 00:00:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sedes generated by hbm2java
 */
public class Sedes  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set solicitudeses = new HashSet(0);
     private Set usuarioses = new HashSet(0);

    public Sedes() {
    }

    public Sedes(String nombre, Set solicitudeses, Set usuarioses) {
       this.nombre = nombre;
       this.solicitudeses = solicitudeses;
       this.usuarioses = usuarioses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getSolicitudeses() {
        return this.solicitudeses;
    }
    
    public void setSolicitudeses(Set solicitudeses) {
        this.solicitudeses = solicitudeses;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


