package model.entities;
// Generated May 17, 2015 2:44:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sedes generated by hbm2java
 */
public class Sedes  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set solicitudeses = new HashSet(0);

    public Sedes() {
    }

    public Sedes(String nombre, Set solicitudeses) {
       this.nombre = nombre;
       this.solicitudeses = solicitudeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getSolicitudeses() {
        return this.solicitudeses;
    }
    
    public void setSolicitudeses(Set solicitudeses) {
        this.solicitudeses = solicitudeses;
    }




}


