package model.entities;
// Generated 12-Jun-2015 00:00:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Solicitudes generated by hbm2java
 */
public class Solicitudes  implements java.io.Serializable {


     private int id;
     private Sedes sedes;
     private short tipo;
     private Date fechaAlta;
     private String observaciones;
     private int numeroSolicitud;
     private Set designacioneses = new HashSet(0);
     private Set comprobanteses = new HashSet(0);
     private Set docenteses = new HashSet(0);
     private Set liquidacioneses = new HashSet(0);
     private Set registrosUnicoses = new HashSet(0);
     private Set expedientesSolicitudeses = new HashSet(0);

    public Solicitudes() {
    }

	
    public Solicitudes(short tipo, int numeroSolicitud) {
        this.tipo = tipo;
        this.numeroSolicitud = numeroSolicitud;
    }
    public Solicitudes(Sedes sedes, short tipo, Date fechaAlta, String observaciones, int numeroSolicitud, Set designacioneses, Set comprobanteses, Set docenteses, Set liquidacioneses, Set registrosUnicoses, Set expedientesSolicitudeses) {
       this.sedes = sedes;
       this.tipo = tipo;
       this.fechaAlta = fechaAlta;
       this.observaciones = observaciones;
       this.numeroSolicitud = numeroSolicitud;
       this.designacioneses = designacioneses;
       this.comprobanteses = comprobanteses;
       this.docenteses = docenteses;
       this.liquidacioneses = liquidacioneses;
       this.registrosUnicoses = registrosUnicoses;
       this.expedientesSolicitudeses = expedientesSolicitudeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Sedes getSedes() {
        return this.sedes;
    }
    
    public void setSedes(Sedes sedes) {
        this.sedes = sedes;
    }
    public short getTipo() {
        return this.tipo;
    }
    
    public void setTipo(short tipo) {
        this.tipo = tipo;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public int getNumeroSolicitud() {
        return this.numeroSolicitud;
    }
    
    public void setNumeroSolicitud(int numeroSolicitud) {
        this.numeroSolicitud = numeroSolicitud;
    }
    public Set getDesignacioneses() {
        return this.designacioneses;
    }
    
    public void setDesignacioneses(Set designacioneses) {
        this.designacioneses = designacioneses;
    }
    public Set getComprobanteses() {
        return this.comprobanteses;
    }
    
    public void setComprobanteses(Set comprobanteses) {
        this.comprobanteses = comprobanteses;
    }
    public Set getDocenteses() {
        return this.docenteses;
    }
    
    public void setDocenteses(Set docenteses) {
        this.docenteses = docenteses;
    }
    public Set getLiquidacioneses() {
        return this.liquidacioneses;
    }
    
    public void setLiquidacioneses(Set liquidacioneses) {
        this.liquidacioneses = liquidacioneses;
    }
    public Set getRegistrosUnicoses() {
        return this.registrosUnicoses;
    }
    
    public void setRegistrosUnicoses(Set registrosUnicoses) {
        this.registrosUnicoses = registrosUnicoses;
    }
    public Set getExpedientesSolicitudeses() {
        return this.expedientesSolicitudeses;
    }
    
    public void setExpedientesSolicitudeses(Set expedientesSolicitudeses) {
        this.expedientesSolicitudeses = expedientesSolicitudeses;
    }




}


