package model.entities;
// Generated 12-Jun-2015 00:00:28 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int id;
     private Areas areas;
     private Sedes sedes;
     private String nombre;
     private String password;
     private String user;
     private Set reSolCones = new HashSet(0);
     
    public Usuarios() {
    }

	
    public Usuarios(Areas areas, Sedes sedes) {
        this.areas = areas;
        this.sedes = sedes;
    }
    public Usuarios(Areas areas, Sedes sedes, String nombre, String password, String user) {
       this.areas = areas;
       this.sedes = sedes;
       this.nombre = nombre;
       this.password = password;
       this.user = user;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Areas getAreas() {
        return this.areas;
    }
    
    public void setAreas(Areas areas) {
        this.areas = areas;
    }
    public Sedes getSedes() {
        return this.sedes;
    }
    
    public void setSedes(Sedes sedes) {
        this.sedes = sedes;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }

    public Set getReSolCones() {
        return reSolCones;
    }

    public void setReSolCones(Set regSolCones) {
        this.reSolCones = regSolCones;
    }
    
    

}


