package model.entities;
// Generated May 17, 2015 2:44:47 AM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int id;
     private Areas areas;
     private String nombre;
     private String password;
     private String user;

    public Usuarios() {
    }

	
    public Usuarios(int id, Areas areas) {
        this.id = id;
        this.areas = areas;
    }
    public Usuarios(int id, Areas areas, String nombre, String password, String user) {
       this.id = id;
       this.areas = areas;
       this.nombre = nombre;
       this.password = password;
       this.user = user;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Areas getAreas() {
        return this.areas;
    }
    
    public void setAreas(Areas areas) {
        this.areas = areas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }




}


