package kakan.entities;
// Generated 13-Jun-2015 04:06:31 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * SpgDocentes generated by hbm2java
 */
public class SpgDocentes  implements java.io.Serializable {


     private int id;
     private Integer nroLegajo;
     private String apellido;
     private String nombre;
     private String tipoDocumento;
     private String documento;
     private String cuil;
     private String sexo;
     private Date fechaAlta;
     private String idProvincia;
     private BigDecimal idCiudad;
     private String barrio;
     private String calle;
     private String numero;
     private String piso;
     private String depto;
     private String telefonoFijo;
     private String telefonoCelular;
     private String mail;
     private String estado;
     private Integer concursoCargo;
     private Date fechaPrimerConcurso;
     private Integer antiguedad;
     private String nivelEstudio;
     private String actividades;
     private Date fechaNacim;
     private Integer edad;
     private Integer puntajeExterno;
     private Date fechaIngreso;
     private String residencia;
     
    public SpgDocentes() {
    }

	
    public SpgDocentes(int id) {
        this.id = id;
    }

    public SpgDocentes(String apellido, String nombre, String documento, String residencia,String mail, String telF, String telC, String cuil) {
        this.apellido = apellido;
        this.nombre = nombre;
        this.documento = documento;
        this.residencia = residencia;
        this.mail = mail;
        this.telefonoCelular = telC;
        this.telefonoFijo = telF;
        this.cuil = cuil;
    }
    
    public SpgDocentes(int id, Integer nroLegajo, String apellido, String nombre, String tipoDocumento, String documento, String cuil, String sexo, Date fechaAlta, String idProvincia, BigDecimal idCiudad, String barrio, String calle, String numero, String piso, String depto, String telefonoFijo, String telefonoCelular, String mail, String estado, Integer concursoCargo, Date fechaPrimerConcurso, Integer antiguedad, String nivelEstudio, String actividades, Date fechaNacim, Integer edad, Integer puntajeExterno, Date fechaIngreso) {
       this.id = id;
       this.nroLegajo = nroLegajo;
       this.apellido = apellido;
       this.nombre = nombre;
       this.tipoDocumento = tipoDocumento;
       this.documento = documento;
       this.cuil = cuil;
       this.sexo = sexo;
       this.fechaAlta = fechaAlta;
       this.idProvincia = idProvincia;
       this.idCiudad = idCiudad;
       this.barrio = barrio;
       this.calle = calle;
       this.numero = numero;
       this.piso = piso;
       this.depto = depto;
       this.telefonoFijo = telefonoFijo;
       this.telefonoCelular = telefonoCelular;
       this.mail = mail;
       this.estado = estado;
       this.concursoCargo = concursoCargo;
       this.fechaPrimerConcurso = fechaPrimerConcurso;
       this.antiguedad = antiguedad;
       this.nivelEstudio = nivelEstudio;
       this.actividades = actividades;
       this.fechaNacim = fechaNacim;
       this.edad = edad;
       this.puntajeExterno = puntajeExterno;
       this.fechaIngreso = fechaIngreso;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getNroLegajo() {
        return this.nroLegajo;
    }
    
    public void setNroLegajo(Integer nroLegajo) {
        this.nroLegajo = nroLegajo;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getCuil() {
        return this.cuil;
    }
    
    public void setCuil(String cuil) {
        this.cuil = cuil;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(String idProvincia) {
        this.idProvincia = idProvincia;
    }
    public BigDecimal getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(BigDecimal idCiudad) {
        this.idCiudad = idCiudad;
    }
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }
    public String getDepto() {
        return this.depto;
    }
    
    public void setDepto(String depto) {
        this.depto = depto;
    }
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }
    public String getTelefonoCelular() {
        return this.telefonoCelular;
    }
    
    public void setTelefonoCelular(String telefonoCelular) {
        this.telefonoCelular = telefonoCelular;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getConcursoCargo() {
        return this.concursoCargo;
    }
    
    public void setConcursoCargo(Integer concursoCargo) {
        this.concursoCargo = concursoCargo;
    }
    public Date getFechaPrimerConcurso() {
        return this.fechaPrimerConcurso;
    }
    
    public void setFechaPrimerConcurso(Date fechaPrimerConcurso) {
        this.fechaPrimerConcurso = fechaPrimerConcurso;
    }
    public Integer getAntiguedad() {
        return this.antiguedad;
    }
    
    public void setAntiguedad(Integer antiguedad) {
        this.antiguedad = antiguedad;
    }
    public String getNivelEstudio() {
        return this.nivelEstudio;
    }
    
    public void setNivelEstudio(String nivelEstudio) {
        this.nivelEstudio = nivelEstudio;
    }
    public String getActividades() {
        return this.actividades;
    }
    
    public void setActividades(String actividades) {
        this.actividades = actividades;
    }
    public Date getFechaNacim() {
        return this.fechaNacim;
    }
    
    public void setFechaNacim(Date fechaNacim) {
        this.fechaNacim = fechaNacim;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Integer getPuntajeExterno() {
        return this.puntajeExterno;
    }
    
    public void setPuntajeExterno(Integer puntajeExterno) {
        this.puntajeExterno = puntajeExterno;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    public String getResidencia() {
        return residencia;
    }

    public void setResidencia(String residencia) {
        this.residencia = residencia;
    }

    

}


