package kakan.entities;
// Generated 13-Jun-2015 04:00:04 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VOgagtd generated by hbm2java
 */
public class VOgagtd  implements java.io.Serializable {

     private String idCategoria;
     private String estado;
     private String categoriaInvestigacion;
     private String idCaracterLiquidacion;
     private Integer idPeriodo;
     private Integer nro;
     private Integer anioAcademico;
     private String periodo;
     private Integer comision;
     private Integer id;
     private Long idDocente;
     private Short idDepartamento;
     private String nombreDpto;
     private Short idUnidadAcademica;
     private String nombreSede;
     private String apellido;
     private String nombre;
     private String dni;
     private String tipoDocumento;
     private String documento;
     private String nombreCategoria;
     private String cargo;
     private String dedicacion;
     private String resComp;
     private String nombreCaracter;
     private String unidadAcademica;
     private String nombreUnidadAcademica;
     private String carrera;
     private String nombreCarrera;
     private String plan;
     private String nroResolucion;
     private String materia;
     private String nombreMateria;
     private Integer anio;
     private String periodoLectivo;
     private String reg;
     private String extension;
     private String emisorNorma;
     private String norma;
     private Long nroNorma;
     private Date fecNorma;
     private String actExtension;
     private String proyInvestigacion;
     private String actGestion;
     private String formRrhh;
     private String observaciones;
     private String descripcionProyectoInvestigacion;
     private String descripcionProyectoExtencion;
     private String descripcionActividadGestion;
     private String descripcionRrhh;
     private Date fechaInicio;
     private Date fechaFin;
     private Integer aumentoDedicacion;
     private String tipoDedicacion;
     private String info;
     private String estadoActual;
     private String instituto;
     private String leyenda;
     private String ambitoLaboral;
     private String centroInvestigacion;
     private String dptoMateria;

    public VOgagtd() {
    }

    public VOgagtd(String idCategoria, String estado, String categoriaInvestigacion, String idCaracterLiquidacion, Integer idPeriodo, Integer nro, Integer anioAcademico, String periodo, Integer comision, Integer id, Long idDocente, Short idDepartamento, String nombreDpto, Short idUnidadAcademica, String nombreSede, String apellido, String nombre, String dni, String tipoDocumento, String documento, String nombreCategoria, String cargo, String dedicacion, String resComp, String nombreCaracter, String unidadAcademica, String nombreUnidadAcademica, String carrera, String nombreCarrera, String plan, String nroResolucion, String materia, String nombreMateria, Integer anio, String periodoLectivo, String reg, String extension, String emisorNorma, String norma, Long nroNorma, Date fecNorma, String actExtension, String proyInvestigacion, String actGestion, String formRrhh, String observaciones, String descripcionProyectoInvestigacion, String descripcionProyectoExtencion, String descripcionActividadGestion, String descripcionRrhh, Date fechaInicio, Date fechaFin, Integer aumentoDedicacion, String tipoDedicacion, String info, String estadoActual, String instituto, String leyenda, String ambitoLaboral, String centroInvestigacion, String dptoMateria) {
       this.idCategoria = idCategoria;
       this.estado = estado;
       this.categoriaInvestigacion = categoriaInvestigacion;
       this.idCaracterLiquidacion = idCaracterLiquidacion;
       this.idPeriodo = idPeriodo;
       this.nro = nro;
       this.anioAcademico = anioAcademico;
       this.periodo = periodo;
       this.comision = comision;
       this.id = id;
       this.idDocente = idDocente;
       this.idDepartamento = idDepartamento;
       this.nombreDpto = nombreDpto;
       this.idUnidadAcademica = idUnidadAcademica;
       this.nombreSede = nombreSede;
       this.apellido = apellido;
       this.nombre = nombre;
       this.dni = dni;
       this.tipoDocumento = tipoDocumento;
       this.documento = documento;
       this.nombreCategoria = nombreCategoria;
       this.cargo = cargo;
       this.dedicacion = dedicacion;
       this.resComp = resComp;
       this.nombreCaracter = nombreCaracter;
       this.unidadAcademica = unidadAcademica;
       this.nombreUnidadAcademica = nombreUnidadAcademica;
       this.carrera = carrera;
       this.nombreCarrera = nombreCarrera;
       this.plan = plan;
       this.nroResolucion = nroResolucion;
       this.materia = materia;
       this.nombreMateria = nombreMateria;
       this.anio = anio;
       this.periodoLectivo = periodoLectivo;
       this.reg = reg;
       this.extension = extension;
       this.emisorNorma = emisorNorma;
       this.norma = norma;
       this.nroNorma = nroNorma;
       this.fecNorma = fecNorma;
       this.actExtension = actExtension;
       this.proyInvestigacion = proyInvestigacion;
       this.actGestion = actGestion;
       this.formRrhh = formRrhh;
       this.observaciones = observaciones;
       this.descripcionProyectoInvestigacion = descripcionProyectoInvestigacion;
       this.descripcionProyectoExtencion = descripcionProyectoExtencion;
       this.descripcionActividadGestion = descripcionActividadGestion;
       this.descripcionRrhh = descripcionRrhh;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.aumentoDedicacion = aumentoDedicacion;
       this.tipoDedicacion = tipoDedicacion;
       this.info = info;
       this.estadoActual = estadoActual;
       this.instituto = instituto;
       this.leyenda = leyenda;
       this.ambitoLaboral = ambitoLaboral;
       this.centroInvestigacion = centroInvestigacion;
       this.dptoMateria = dptoMateria;
    }
   
    public String getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(String idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCategoriaInvestigacion() {
        return this.categoriaInvestigacion;
    }
    
    public void setCategoriaInvestigacion(String categoriaInvestigacion) {
        this.categoriaInvestigacion = categoriaInvestigacion;
    }
    public String getIdCaracterLiquidacion() {
        return this.idCaracterLiquidacion;
    }
    
    public void setIdCaracterLiquidacion(String idCaracterLiquidacion) {
        this.idCaracterLiquidacion = idCaracterLiquidacion;
    }
    public Integer getIdPeriodo() {
        return this.idPeriodo;
    }
    
    public void setIdPeriodo(Integer idPeriodo) {
        this.idPeriodo = idPeriodo;
    }
    public Integer getNro() {
        return this.nro;
    }
    
    public void setNro(Integer nro) {
        this.nro = nro;
    }
    public Integer getAnioAcademico() {
        return this.anioAcademico;
    }
    
    public void setAnioAcademico(Integer anioAcademico) {
        this.anioAcademico = anioAcademico;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public Integer getComision() {
        return this.comision;
    }
    
    public void setComision(Integer comision) {
        this.comision = comision;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Long getIdDocente() {
        return this.idDocente;
    }
    
    public void setIdDocente(Long idDocente) {
        this.idDocente = idDocente;
    }
    public Short getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Short idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNombreDpto() {
        return this.nombreDpto;
    }
    
    public void setNombreDpto(String nombreDpto) {
        this.nombreDpto = nombreDpto;
    }
    public Short getIdUnidadAcademica() {
        return this.idUnidadAcademica;
    }
    
    public void setIdUnidadAcademica(Short idUnidadAcademica) {
        this.idUnidadAcademica = idUnidadAcademica;
    }
    public String getNombreSede() {
        return this.nombreSede;
    }
    
    public void setNombreSede(String nombreSede) {
        this.nombreSede = nombreSede;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getDedicacion() {
        return this.dedicacion;
    }
    
    public void setDedicacion(String dedicacion) {
        this.dedicacion = dedicacion;
    }
    public String getResComp() {
        return this.resComp;
    }
    
    public void setResComp(String resComp) {
        this.resComp = resComp;
    }
    public String getNombreCaracter() {
        return this.nombreCaracter;
    }
    
    public void setNombreCaracter(String nombreCaracter) {
        this.nombreCaracter = nombreCaracter;
    }
    public String getUnidadAcademica() {
        return this.unidadAcademica;
    }
    
    public void setUnidadAcademica(String unidadAcademica) {
        this.unidadAcademica = unidadAcademica;
    }
    public String getNombreUnidadAcademica() {
        return this.nombreUnidadAcademica;
    }
    
    public void setNombreUnidadAcademica(String nombreUnidadAcademica) {
        this.nombreUnidadAcademica = nombreUnidadAcademica;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public String getNombreCarrera() {
        return this.nombreCarrera;
    }
    
    public void setNombreCarrera(String nombreCarrera) {
        this.nombreCarrera = nombreCarrera;
    }
    public String getPlan() {
        return this.plan;
    }
    
    public void setPlan(String plan) {
        this.plan = plan;
    }
    public String getNroResolucion() {
        return this.nroResolucion;
    }
    
    public void setNroResolucion(String nroResolucion) {
        this.nroResolucion = nroResolucion;
    }
    public String getMateria() {
        return this.materia;
    }
    
    public void setMateria(String materia) {
        this.materia = materia;
    }
    public String getNombreMateria() {
        return this.nombreMateria;
    }
    
    public void setNombreMateria(String nombreMateria) {
        this.nombreMateria = nombreMateria;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }
    public String getPeriodoLectivo() {
        return this.periodoLectivo;
    }
    
    public void setPeriodoLectivo(String periodoLectivo) {
        this.periodoLectivo = periodoLectivo;
    }
    public String getReg() {
        return this.reg;
    }
    
    public void setReg(String reg) {
        this.reg = reg;
    }
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }
    public String getEmisorNorma() {
        return this.emisorNorma;
    }
    
    public void setEmisorNorma(String emisorNorma) {
        this.emisorNorma = emisorNorma;
    }
    public String getNorma() {
        return this.norma;
    }
    
    public void setNorma(String norma) {
        this.norma = norma;
    }
    public Long getNroNorma() {
        return this.nroNorma;
    }
    
    public void setNroNorma(Long nroNorma) {
        this.nroNorma = nroNorma;
    }
    public Date getFecNorma() {
        return this.fecNorma;
    }
    
    public void setFecNorma(Date fecNorma) {
        this.fecNorma = fecNorma;
    }
    public String getActExtension() {
        return this.actExtension;
    }
    
    public void setActExtension(String actExtension) {
        this.actExtension = actExtension;
    }
    public String getProyInvestigacion() {
        return this.proyInvestigacion;
    }
    
    public void setProyInvestigacion(String proyInvestigacion) {
        this.proyInvestigacion = proyInvestigacion;
    }
    public String getActGestion() {
        return this.actGestion;
    }
    
    public void setActGestion(String actGestion) {
        this.actGestion = actGestion;
    }
    public String getFormRrhh() {
        return this.formRrhh;
    }
    
    public void setFormRrhh(String formRrhh) {
        this.formRrhh = formRrhh;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getDescripcionProyectoInvestigacion() {
        return this.descripcionProyectoInvestigacion;
    }
    
    public void setDescripcionProyectoInvestigacion(String descripcionProyectoInvestigacion) {
        this.descripcionProyectoInvestigacion = descripcionProyectoInvestigacion;
    }
    public String getDescripcionProyectoExtencion() {
        return this.descripcionProyectoExtencion;
    }
    
    public void setDescripcionProyectoExtencion(String descripcionProyectoExtencion) {
        this.descripcionProyectoExtencion = descripcionProyectoExtencion;
    }
    public String getDescripcionActividadGestion() {
        return this.descripcionActividadGestion;
    }
    
    public void setDescripcionActividadGestion(String descripcionActividadGestion) {
        this.descripcionActividadGestion = descripcionActividadGestion;
    }
    public String getDescripcionRrhh() {
        return this.descripcionRrhh;
    }
    
    public void setDescripcionRrhh(String descripcionRrhh) {
        this.descripcionRrhh = descripcionRrhh;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Integer getAumentoDedicacion() {
        return this.aumentoDedicacion;
    }
    
    public void setAumentoDedicacion(Integer aumentoDedicacion) {
        this.aumentoDedicacion = aumentoDedicacion;
    }
    public String getTipoDedicacion() {
        return this.tipoDedicacion;
    }
    
    public void setTipoDedicacion(String tipoDedicacion) {
        this.tipoDedicacion = tipoDedicacion;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public String getEstadoActual() {
        return this.estadoActual;
    }
    
    public void setEstadoActual(String estadoActual) {
        this.estadoActual = estadoActual;
    }
    public String getInstituto() {
        return this.instituto;
    }
    
    public void setInstituto(String instituto) {
        this.instituto = instituto;
    }
    public String getLeyenda() {
        return this.leyenda;
    }
    
    public void setLeyenda(String leyenda) {
        this.leyenda = leyenda;
    }
    public String getAmbitoLaboral() {
        return this.ambitoLaboral;
    }
    
    public void setAmbitoLaboral(String ambitoLaboral) {
        this.ambitoLaboral = ambitoLaboral;
    }
    public String getCentroInvestigacion() {
        return this.centroInvestigacion;
    }
    
    public void setCentroInvestigacion(String centroInvestigacion) {
        this.centroInvestigacion = centroInvestigacion;
    }
    public String getDptoMateria() {
        return this.dptoMateria;
    }
    
    public void setDptoMateria(String dptoMateria) {
        this.dptoMateria = dptoMateria;
    }




}


